(() => {'use strict';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const progress=$('#progress'), nav=$('#nav'), loader=$('#loader');
window.addEventListener('load',()=>setTimeout(()=>loader?.classList.add('done'),650));
function scrollUI(){const max=document.documentElement.scrollHeight-innerHeight; if(progress) progress.style.width=(max>0?scrollY/max*100:0)+'%'; nav?.classList.toggle('scrolled',scrollY>40)}
addEventListener('scroll',scrollUI,{passive:true}); scrollUI();
const menu=$('#menu'), panel=$('#menuPanel');
menu?.addEventListener('click',()=>{const open=panel.classList.toggle('open');menu.classList.toggle('is-open',open);menu.setAttribute('aria-expanded',open)});
$$('#menuPanel a').forEach(a=>a.addEventListener('click',()=>{panel.classList.remove('open');menu?.classList.remove('is-open')}));
const cursor=$('#cursor'),ring=$('#cursorRing');
if(cursor&&ring&&!reduce&&matchMedia('(hover:hover)').matches){let x=innerWidth/2,y=innerHeight/2,rx=x,ry=y;addEventListener('pointermove',e=>{x=e.clientX;y=e.clientY});function tick(){rx+=(x-rx)*.2;ry+=(y-ry)*.2;cursor.style.left=x+'px';cursor.style.top=y+'px';ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(tick)}tick();$$('.magnetic,a,button,summary').forEach(el=>{el.addEventListener('mouseenter',()=>ring.classList.add('is-hover'));el.addEventListener('mouseleave',()=>ring.classList.remove('is-hover'))})}
if(!reduce&&matchMedia('(hover:hover)').matches){$$('[data-tilt]').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateX(${y*-5}deg) rotateY(${x*5}deg) translateY(-5px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
const reveals=$$('.section-pad,.service-row,.process-item,.work,.price-card,.faq-list,.quote-section,.final-cta'); if(!reduce){reveals.forEach((el,i)=>{el.style.opacity='0';el.style.transform='translateY(25px)';el.style.transition=`opacity .8s cubic-bezier(.16,1,.3,1) ${i%5*.05}s,transform .8s cubic-bezier(.16,1,.3,1) ${i%5*.05}s`});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.style.opacity='1';e.target.style.transform='none';io.unobserve(e.target)}}),{threshold:.08});reveals.forEach(e=>io.observe(e))}
const processItems=$$('.process-item'),meter=$('#processMeter');if(processItems.length){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const i=processItems.indexOf(e.target);processItems.forEach(x=>x.classList.remove('is-active'));e.target.classList.add('is-active');if(meter)meter.style.width=((i+1)/processItems.length*100)+'%'}}),{threshold:.55});processItems.forEach(x=>io.observe(x))}
const stage=$('.stage-window');if(stage&&!reduce){let sy=0;addEventListener('scroll',()=>{const r=stage.getBoundingClientRect();const center=innerHeight/2;sy=(center-(r.top+r.height/2))*0.015;stage.style.transform=`perspective(1200px) rotateX(${Math.max(-2,Math.min(2,sy))}deg) rotateY(${Math.max(-2,Math.min(2,scrollY*.002%2))}deg)`},{passive:true})}
const form=$('#orderForm');
if(form){const packages={starter:{name:'Starter',base:3500000,days:'5–7 hari',inc:['1 halaman utama','Responsive design','Revisi 2x']},profesional:{name:'Profesional',base:8500000,days:'10–14 hari',inc:['Sampai 6 halaman','Custom visual system','Revisi 4x']},enterprise:{name:'Enterprise',base:18000000,days:'Custom',inc:['Fitur custom','API / system integration','Support 30 hari'],from:true}};const rupiah=n=>'Rp '+Math.round(n).toLocaleString('id-ID');const name=$('#summaryName'),price=$('#summaryPrice'),incs=$('#summaryIncludes'),dp=$('#summaryDP'),rem=$('#summaryRemaining'),days=$('#summaryDays');function update(){const key=form.querySelector('[name=package]:checked')?.value||'profesional',p=packages[key],pre=p.from?'Mulai ':'';if(name)name.textContent=p.name;if(price)price.textContent=pre+rupiah(p.base);if(dp)dp.textContent=pre+rupiah(p.base*.1);if(rem)rem.textContent=pre+rupiah(p.base*.9);if(days)days.textContent=p.days;if(incs)incs.innerHTML=p.inc.map(x=>`<li>${x}</li>`).join('')}form.querySelectorAll('[name=package]').forEach(x=>x.addEventListener('change',update));const q=new URLSearchParams(location.search).get('paket');if(packages[q]){const r=form.querySelector(`[name=package][value="${q}"]`);if(r)r.checked=true}update();form.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const key=form.querySelector('[name=package]:checked').value,p=packages[key];$('#confName').textContent=$('#fullName').value.trim();$('#confPackage').textContent=p.name;form.parentElement.hidden=true;$('.order-summary')?.setAttribute('hidden','');$('#confirmationPanel').hidden=false;$('#confirmationPanel').scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})})}
})();
